# Generated by Django 2.2.4 on 2019-09-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofuncionarioform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registrofuncionarioform',
            name='password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
