# Generated by Django 2.2.4 on 2019-09-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190913_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPacienteForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
