# Generated by Django 2.2.7 on 2019-11-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registropacienteform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroFuncionarioForm',
        ),
        migrations.DeleteModel(
            name='RegistroPacienteForm',
        ),
    ]
