FROM python:3.7

ENV DJANGO_SETTINGS_MODULE hospitalizaciondomiciliaria.production

ENV PYTHONUNBUFFERED 1

RUN mkdir hospitalizaciondomiciliaria

WORKDIR /hospitalizaciondomiciliaria

ADD . /hospitalizaciondomiciliaria

RUN ./setup.sh

ENTRYPOINT ["./start.sh"]

EXPOSE 80