# Generated by Django 2.2.7 on 2019-11-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFuncionarioForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idVisit', models.IntegerField(unique=True)),
                ('idPatient', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Visita')),
                ('nextVisit', models.DateField(verbose_name='Proxima Visita')),
            ],
        ),
    ]
