# Generated by Django 2.2.1 on 2019-09-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroFuncionarioForm',
            new_name='ReporteFuncionario',
        ),
    ]
