# Generated by Django 2.2.7 on 2019-11-26 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20190913_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReporteFuncionario',
        ),
    ]
