# Generated by Django 2.2.7 on 2019-11-24 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactoHospital', models.IntegerField()),
                ('Documento_PDF', models.FileField(upload_to='media/files')),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parentezco', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Personales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Primer_Nombre', models.CharField(max_length=45)),
                ('Segundo_Nombre', models.CharField(max_length=45)),
                ('Apellido_Paterno', models.CharField(max_length=45)),
                ('Apellido_Materno', models.CharField(max_length=45)),
                ('Domicilio', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=15)),
                ('Rut', models.CharField(max_length=10)),
                ('Nacionalidad', models.CharField(max_length=20)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Comuna', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=45)),
                ('IdCuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hora_Inicio', models.DateField()),
                ('Hora_Termino', models.DateField()),
                ('Fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Horario_Visita', models.DateField()),
                ('Presencia', models.BooleanField(default=False)),
                ('Dia_Visitado', models.DateField()),
                ('Reporte', models.CharField(max_length=800)),
                ('Fotos_Heridas', models.ImageField(upload_to='media/images/visita')),
                ('Secuencia', models.IntegerField()),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Paciente')),
                ('idRuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Contraseña', models.CharField(max_length=20)),
                ('Tipo_Usuario', models.IntegerField()),
                ('Mail', models.CharField(max_length=45)),
                ('idDatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Datos_Personales')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_Medica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto_Avance_Medico', models.ImageField(upload_to='media/images/ficha-medica')),
                ('Historia', models.CharField(max_length=200)),
                ('Insumo', models.CharField(max_length=45)),
                ('Cant_Insumo', models.IntegerField()),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdRuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ruta')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cuidador',
            name='IdUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proxima_Visita', models.DateField()),
                ('IdCuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cuidador')),
            ],
        ),
    ]
