# Generated by Django 2.2.7 on 2019-11-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191125_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='Dia_Visitado',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='Fotos_Heridas',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/visita'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='Horario_Visita',
            field=models.TimeField(),
        ),
    ]
