# Generated by Django 2.2.7 on 2019-11-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191125_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='Dia_Visitado',
            field=models.DateField(auto_now=True),
        ),
    ]
