# Generated by Django 2.2.7 on 2019-11-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191125_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='Dia_Visitado',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creacion'),
        ),
    ]
