# Generated by Django 2.2.7 on 2019-11-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191125_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='Dia_Visitado',
            field=models.DateField(verbose_name='Fecha de creacion'),
        ),
    ]
