# Generated by Django 2.2.7 on 2019-11-26 03:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191125_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendario',
            old_name='IdCuidador',
            new_name='idCuidador',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='IdRuta',
            new_name='idRuta',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='IdUsuario',
            new_name='idUsuario',
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='Documento_PDF',
            field=models.FileField(blank=True, null=True, upload_to='media/files'),
        ),
        migrations.AlterField(
            model_name='ficha_medica',
            name='Foto_Avance_Medico',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/ficha-medica'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='Dia_Visitado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
