# Generated by Django 2.2.1 on 2020-02-23 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191126_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idDatos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Datos_Personales'),
        ),
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitud', models.IntegerField()),
                ('Longitud', models.IntegerField()),
                ('idDatos_Personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Datos_Personales')),
            ],
        ),
    ]
