# Generated by Django 2.2.1 on 2020-03-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200307_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenada',
            name='Latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='coordenada',
            name='Longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
