# Generated by Django 2.2.1 on 2019-06-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ruta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
