# Generated by Django 2.2.1 on 2019-06-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='ruta',
            field=models.IntegerField(default=0),
        ),
    ]
