# Generated by Django 2.2.1 on 2019-06-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20190622_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Ruta'),
        ),
    ]
