# Generated by Django 2.2.1 on 2019-06-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_auto_20190624_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='ruta',
        ),
    ]
