# Generated by Django 2.2.1 on 2019-06-24 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_remove_paciente_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ruta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Ruta'),
        ),
    ]
