# Generated by Django 2.2.1 on 2019-06-24 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_paciente_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='ruta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Ruta'),
        ),
    ]
