# Generated by Django 2.2.1 on 2019-06-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_auto_20190624_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='ruta',
            field=models.ForeignKey(on_delete=models.SET(17), to='pacientes.Ruta'),
        ),
    ]
